### ISSUE TITLE
План работы в команде на ближайшие две недели

### ISSUE THREAD

**Issue by SeveralCamper** [trpo2021/cw-ip-014_conway-s-game-of-life#11]
- [x] Коммуникацию проводим через обсуждение в данной теме.

- [x] Ознакомилась? - Ставь галочку.

- [x] Вопросы\ответы по материалам работы скидываем в отдельные темы.

- [x] Отчеты о выполненной работе приписываем сюда.

**Comment by SeveralCamper** [comment]
Я занимаюсь разработкой структуры и логики программы: на моей части будет ООП, мейк и тесты с тобой пополам
Тебе нужно будет разобраться с SFML и прикрутить к нашей проге красивую картинку + тесты + какие-то обязанности по проге я буду делегировать тебе

**Comment by Astip3** [comment]
План работы принят. 
Все намеченные в Т.З. задачи: интерфейс, игровое поле, режим моделей будут сделаны в ближайшее время. 
Далее перейду к разработке тестов.

**Comment by SeveralCamper** [comment]
Makefile готов, можно преступать к работе над своими областями! Я разработаю костяк, потом разбегаемся по веткам и работаем. По вопросам в дис

**Comment by Astip3** [comment]
_Создала_ новую тестовую ветку для графики, добавила пробное меню.
_В перспективе_ доработка выбора режимов игры, улучшение визуальной стороны, так как сейчас сделан черновик (примерное расположение).

**ВАЖНО!** Обсудить расположение кнопок и игрового поля.
Если есть замечания, то рада учесть!

**Comment by Astip3** [comment]
![image](https://user-images.githubusercontent.com/78479541/119709879-e6625b00-be87-11eb-983e-cd1708bfa243.png)

**Comment by SeveralCamper** [comment]
Я понемногу заканчиваю логику программы. Что-то даже получается
В скором времени нам нужно будет скооперироваться, чтобы совместно разработать слияние логики и графики. Предположительно сегодня вечером\завтра

**Comment by Astip3** [comment]
Предложение принято. Сегодня заканчиваю разработку меню, а завтра сконцентрируемся на слиянии наших работ.

**Comment by SeveralCamper** [comment]
Меня неопределенные ссылки опять душат...

**Comment by Astip3** [comment]
Оцените рамку с кнопками

**Comment by SeveralCamper** [comment]
Я сделал очень крутую вещь: с помощью enum class теперь есть массив состояний и красивая картинка :). Да и код читабельней, благо в лабах я уже этим развлекался
![image](https://user-images.githubusercontent.com/78479277/120038034-d33cc000-c02c-11eb-9945-9249910da5ba.png)

**Comment by SeveralCamper** [comment]
Как октрыт эссе?
