### ISSUE TITLE
Тема SFML

### ISSUE THREAD

**Issue by SeveralCamper** [trpo2021/cw-ip-014_conway-s-game-of-life#13]
- [x] https://habr.com/ru/post/278977/

Оч хороший канал по CPP, лайк челу
- [x] https://www.youtube.com/watch?v=DweFb9btMVo
- [x] https://kychka-pc.ru/sfml/urok-2-razbor-testovogo-koda-osnovnoj-princip-raboty-sfml-obyazatelnye-funkcii-sfml.html

**Comment by Astip3** [comment]
**_Пользуюсь данными уроками для изучения:_**

(в процессе список будет пополняться)
(P.S. следите за обновлениями)
- [ ] https://kychka-pc.ru/sfml/urok-2-razbor-testovogo-koda-osnovnoj-princip-raboty-sfml-obyazatelnye-funkcii-sfml.html
