### ISSUE TITLE
План работы в команде на ближайшие пару дней

### ISSUE THREAD

**Issue by SeveralCamper** [trpo2021/cw-ip-014_conway-s-game-of-life#15]

**Comment by SeveralCamper** [comment]
Я обнаружил проблему не правильной задачи исходного количества клеток:
![image](https://user-images.githubusercontent.com/78479277/120058629-749c3400-c076-11eb-87e8-270b43cf778d.png)
![image](https://user-images.githubusercontent.com/78479277/120058718-29365580-c077-11eb-9fa9-0823ef215426.png)

**Comment by SeveralCamper** [comment]
Сделал несколько тестов: раз на раз не приходится. Все нормально

**Comment by Astip3** [comment]
Сравнила с твоим окном, сделала рамку по согласованным размерам. Изменила расположение и название кнопок.

В перспективе сделать одну цветовую гамму.
![Снимок экрана от 2021-05-29 16-56-05](https://user-images.githubusercontent.com/78479541/120066051-d8d2ee00-c09e-11eb-85ba-a398cab2f655.png)

**Comment by Astip3** [comment]
_Цветовая гамма интерфейса готова._
![Снимок экрана от 2021-05-29 17-41-00](https://user-images.githubusercontent.com/78479541/120067314-120e5c80-c0a5-11eb-9344-51d1a2ca118c.png)

**Comment by SeveralCamper** [comment]
В связи с тем, что мы не укладываемся в срок, принято решение не добавлять режим моделей.

**Comment by Astip3** [comment]
BETA  версия
(осталась реализация кнопок и интерфейс будет готов)

![Снимок экрана от 2021-05-30 01-22-41](https://user-images.githubusercontent.com/78479541/120081060-bc0dd900-c0e5-11eb-911c-a7d5ff361cf5.png)

**Comment by SeveralCamper** [comment]
Пмгити

**Comment by SeveralCamper** [comment]
Уффф... Я много пропустил того чего я делал, из-за того, что у меня случилось проблема с последним элементом проги... как не странно, ошибки всегда в самом конце. Сейчас мы вместе перерабатываем структуру интерфейса, чтобы привести ее к лучшему виду. Это запись для отчетности

**Comment by SeveralCamper** [comment]
Мы решили разделить полномочия в последнем рывке. Я займусь режимом моделей, а Вера пользовательским режимом. Я ухожу с BETA на новую ветку, там буду продолжать работу.

**Comment by Astip3** [comment]
**Let's go!**

**Comment by SeveralCamper** [comment]
У нас появились важные изменения относительно исходных данных приложения, поэтому я осветили их в Т.З. Продублирую здесь: я решил использовать то, чему нас учили на программировании. Поменялся формат входных данных, а точнее появился. Теперь мы будем считывать модели для режима моделей из файла, в котором будут заданы все модели, которые мы хотим, а также можно будет сделать свою модель в пределах клеток 13х13. Но своих можно будет сделать не так много. Для этого нужно будет просто задать ей имя и написать массив 0 и 1, такой, что каждая 1 = живая клетка, 0 = мертвая.

**Comment by SeveralCamper** [comment]
Вот так это будет выглядеть
![image](https://user-images.githubusercontent.com/78479277/120963155-452eab00-c78b-11eb-859e-5b9e95d5da5f.png)

**Comment by SeveralCamper** [comment]
И снова небольшой сюжетный поворот: общем голосованием из двух членов команды, мы единогласно пришли к тому, чтобы не делать модели.

**Comment by SeveralCamper** [comment]
Закончили!
